# TYPE OF BUILD
CUSTOM_BUILD_TYPE ?= UNOFFICIAL
# OFFICIAL_DEVICES
ifeq ($(CUSTOM_BUILD_TYPE), OFFICIAL)
  LIST = $(shell cat vendor/lineage/spring.devices)
    ifeq ($(filter $(CUSTOM_BUILD), $(LIST)), $(CUSTOM_BUILD))
      IS_OFFICIAL=true
      CUSTOM_BUILD_TYPE := OFFICIAL
    endif
    ifneq ($(IS_OFFICIAL), true)
      CUSTOM_BUILD_TYPE := UNOFFICIAL
      $(error Device is not official "$(CUSTOM_BUILD)")
    endif
endif

# SET BUILD
LINEAGE_BUILD = $(SPRING_BUILD)

# OS SOURCE STATE
SPRING_STATE := BETA

# INTERNAL VERSION
SPRING_VERSION := SpringOS-$(SPRING_BUILD)-$(PLATFORM_VERSION)-$(shell date +%d%m%Y)-$(SPRING_STATE)-$(CUSTOM_BUILD_TYPE)

# DISPLAY VERSION
SPRING_DISPLAY_VERSION := SpringOS-$(SPRING_BUILD)-$(PLATFORM_VERSION)-$(SPRING_STATE)-$(CUSTOM_BUILD_TYPE)