# TYPE OF BUILD
CUSTOM_BUILD_TYPE ?= UNOFFICIAL
# OFFICIAL_DEVICES
ifeq ($(CUSTOM_BUILD_TYPE), OFFICIAL)
  LIST = $(shell cat vendor/lineage/magnus.devices)
    ifeq ($(filter $(CUSTOM_BUILD), $(LIST)), $(CUSTOM_BUILD))
      IS_OFFICIAL=true
      CUSTOM_BUILD_TYPE := OFFICIAL
    endif
    ifneq ($(IS_OFFICIAL), true)
      CUSTOM_BUILD_TYPE := UNOFFICIAL
      $(error Device is not official "$(CUSTOM_BUILD)")
    endif
endif

# SET BUILD
LINEAGE_BUILD = $(MAGNUS_BUILD)

# OS SOURCE STATE
MAGNUS_STATE := BETA

# INTERNAL VERSION
MAGNUS_VERSION := MagnusOS-$(MAGNUS_BUILD)-$(PLATFORM_VERSION)-$(shell date +%d%m%Y)-$(MAGNUS_STATE)-$(CUSTOM_BUILD_TYPE)

# DISPLAY VERSION
MAGNUS_DISPLAY_VERSION := MagnusOS-$(MAGNUS_BUILD)-$(PLATFORM_VERSION)-$(MAGNUS_STATE)-$(CUSTOM_BUILD_TYPE)